[variables]
NIXPACKS_PYTHON_VERSION = "3.13"
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --no-input"]

[start]
cmd = "python3 manage.py migrate --no-input && cd backend && python3 -m gunicorn backend.wsgi:application --host 0.0.0.0 --port $PORT"
