[variables]
NIXPACKS_PYTHON_VERSION = "3.13"

[phases.build]
cmds = [
    "cd backend",
    "python3 -m pip install -r requirements.txt"
]

[phases.deploy]
cmds = [
    "cd backend",
    "python3 manage.py migrate --no-input",
    "python3 manage.py collectstatic --no-input"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --host 0.0.0.0 --port $PORT"
