[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate --no-input && cd backend && python3 -m gunicorn backend.wsgi:application --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NIXPACKS_PYTHON_VERSION = "3.13"
PYTHONPATH = "/app"
